jobs:

#MANIFESTS
      
  - name: flui-man1
    type: manifest
    steps:
      - IN: flui-img1
      - IN: flui-tg1
      
  - name: flui-man2
    type: manifest
    steps:
      - IN: flui-img2
      - IN: flui-tg1
