jobs:
  - name: lb-mani1
    type: manifest
    steps:
      - IN: lb-imglb
      - IN: lb-dopt1
      - IN: lb-params1
      - IN: lb-tg1
    flags:
      - release
      
  - name: lb-ecsDeploy1
    type: deploy
    steps:
      - IN: lb-mani1
      - IN: lb-ecscluster
      - IN: lb-loadb1
        applyTo:
          - manifest: lb-mani1 # it can only apply to one manifest
            image: lb-imglb # it can only apply to one image in the manifest
            port: 80
      - TASK: managed
        deployMethod: upgrade 
        
  - name: lb-release1
    type: release
    steps:
      - IN: lb-version1
      - IN: lb-ecsDeploy1
      - TASK: managed
        bump: patch
        
  - name: lb-ecsDeploy2
    type: deploy
    steps:
      - IN: lb-release1
      - IN: lb-ecscluster
      
  - name: lb-release2
    type: release
    steps:
      - IN: lb-version2
      - IN: lb-ecsDeploy2
      - TASK: managed
        bump: major
        
  - name: lb-mani2
    type: manifest
    steps:
      - IN: lb-imglb2
      - IN: lb-dopt2
      - IN: lb-tg1
    flags:
      - loadbalancer
        
  - name: lb-ecsDeploy3
    type: deploy
    steps:
      - IN: lb-mani2
      - IN: lb-ecscluster2
      - IN: lb-loadb2
        applyTo:
          - manifest: lb-mani2 # it can only apply to one manifest
            image: lb-imglb # it can only apply to one image in the manifest
            port: 80
      - TASK: managed
        deployMethod: upgrade 
