triggers:
   - name: gr-tg1
     type: trigger
     version:
       counter: 0
       
   - name: gr-tg2
     type: trigger
     version:
       counter: 0
       
   - name: gr-tg3
     type: trigger
     version:
       counter: 0
       
   - name: gr-tg4
     type: trigger
     version:
       counter: 0
       
   - name: gr-tg5
     type: trigger
     version:
       counter: 0
