jobs:

#RELEASE

  - name: sr-release
    type: release
    steps:
      - IN: sr-version
      - IN: sr-tg1
      - TASK: managed
        bump: beta
    #- IN: notify-man1cnrimg
      
#MANIFESTS
      
 # - name: sr-man1
  #  type: manifest
   # steps:
    #  - IN: sr-img1
     # - IN: sr-tg1
      
  - name: sr-man2
    type: manifest
    steps:
      - IN: sr-img2
      - IN: sr-tg2
      
  - name: sr-man3
    type: manifest
    steps:
      - IN: sr-img2
      - IN: sr-tg3

#DEPLOYMENTS 

 # - name: sr-ecsdeployup
  #  type: deploy
   # steps:
    #  - IN: sr-man1
     # - IN: sr-ecscluster
      #- TASK: managed
       # deployMethod: upgrade
      
  - name: sr-ecsdeploybg
    type: deploy
    steps:
      - IN: sr-man2
      - IN: sr-ecscluster
