jobs:

#RELEASE

  - name: rs-release
    type: release
    steps:
      - IN: rs-version
      - TASK: managed
        bump: beta
      #- IN: notify-man1cnrimg
      #- IN: triggernotify7

  - name: rs-man1
    type: manifest
    steps:
      - IN: rs-img1
      - IN: rs-tg1
      
  - name: rs-inrunsh
    type: runSh
    steps:
      - IN: rs-sample-script
      - TASK:
        - script: ls
        - script: ./IN/rs-sample-script/rs-sample-script/echo.sh
      #- on_success:
       # - echo 'This block executes after TASK section executes successfully'
       # - NOTIFY: slackNotifcation
