jobs:
#MANIFESTS
      
  - name: gke-man1
    type: manifest
    steps:
      - IN: gke-img1
      - IN: gke-tg1
      
  - name: gke-man2
    type: manifest
    steps:
      - IN: gke-img2
      - IN: gke-tg2
      
  - name: gkeman3-invalidimg
    type: manifest
    steps:
      - IN: gkeimg4-tagdoesntexist
      - IN: gke-tg3
      
  - name: gkeman4-invalid
    type: manifest
    steps:
      - IN: gke-img2
        versionNumber: 369
      - IN: gke-tg4
      
  - name: gke-man5mftomf
    type: manifest
    steps:
      - IN: gke-img1
      - IN: gke-man2
      
  - name: gke-man6multiimg
    type: manifest
    steps:
      - IN: gke-img1
      - IN: gke-img2

# DEPLOYMENTS 

  - name: gke-deploy1up
    type: deploy
    steps:
      - IN: gke-man1
      - IN: gke-cluster
      - TASK: managed
        deployMethod: upgrade
      
  - name: gke-deploy2bginvalidclu
    type: deploy
    steps:
      - IN: gke-man1
      - IN: gkeclu2-invalidclu
      
  - name: gke-deploy3upinvalidimg
    type: deploy
    steps:
      - IN: gkeman3-invalidimg
      - IN: gke-cluster
      - TASK: managed
        deployMethod: upgrade

  - name: gke-deploy4bginvalidmani
    type: deploy
    steps:
      - IN: gkeman4-invalid
      - IN: gke-cluster
      
  - name: gke-deploy5bgmultiimgmani
    type: deploy
    steps:
      - IN: gke-man6multiimg
      - IN: gke-cluster
  
   - name: gke-deploy5bgmftomf
    type: deploy
    steps:
      - IN: gke-man5mftomf
      - IN: gke-cluster  
