triggers:
   - name: flsv-tg1
     type: trigger
     version:
       counter: 1
       
   - name: flsv-tg2
     type: trigger
     version:
       counter: 3
       
   - name: flsv-tg3
     type: trigger
     version:
       counter: 6
       
   - name: flsv-tg4
     type: trigger
     version:
       counter: 3
       
   - name: flsv-tg5
     type: trigger
     version:
       counter: 2
       
   - name: flsv-tg6
     type: trigger
     version:
       counter: 2
       
   - name: flsv-tg7
     type: trigger
     version:
       counter: 1
       
   - name: flsv-tg8
     type: trigger
     version:
       counter: 8
       
   - name: flsv-tg9
     type: trigger
     version:
       counter: 0
       
   - name: flsv-tg10
     type: trigger
     version:
       counter: 1
       
   - name: flsv-tg11
     type: trigger
     version:
       counter: 1
       
   - name: flsv-tg12
     type: trigger
     version:
       counter: 0
