jobs:
  # - name: lb-mani1
  #   type: manifest
  #   steps:
  #     - IN: lb-imglb3
  #   # - IN: lb-dopt1
  #     #- IN: lb-params1
  #     - IN: lb-tg1
  #   flags:
  #     - release
      
  # - name: lb-ecsDeploy1
  #   type: deploy
  #   steps:
  #     - IN: lb-mani1
  #     - IN: lb-dopts3
  #     - IN: lb-ecscluster
  #     - TASK: managed
  #       deployMethod: upgrade 
        
  # - name: lb-release1
  #   type: release
  #   steps:
  #     - IN: lb-version1
  #     - IN: lb-ecsDeploy1
  #     - TASK: managed
  #       bump: patch
        
  # - name: lb-ecsDeploy2
  #   type: deploy
  #   steps:
  #     - IN: lb-release1
  #     - IN: lb-ecscluster
      
  # - name: lb-release2
  #   type: release
  #   steps:
  #     - IN: lb-version2
  #     - IN: lb-ecsDeploy2
  #     - TASK: managed
  #       bump: major
        
  - name: lb-mani2up
    type: manifest
    steps:
      - IN: lb-imglb2
      - IN: lb-dopt1up
      - IN: lb-tg1
    flags:
      - loadbalancerup
      
  - name: lb-mani3bg
    type: manifest
    steps:
      - IN: lb-imglb2
      - IN: lb-dopt2bg
      - IN: lb-tg1
    flags:
      - loadbalancerbg
      
  - name: lb-mani4invalid
    type: manifest
    steps:
      - IN: lb-imglb2
      - IN: lb-dopts2
      - IN: lb-tg2
    flags:
      - loadbalancerinvalid
        
  - name: lb-lbDeploy1up
    type: deploy
    steps:
      - IN: lb-mani2up
      - IN: lb-ecscluster2
      - IN: lb-loadb1up
        applyTo:
          - manifest: lb-mani2up # it can only apply to one manifest
            image: lb-imglb2 # it can only apply to one image in the manifest
            port: 80
      - TASK: managed
        deployMethod: upgrade 
        
  - name: lb-lbDeploy2bg
    type: deploy
    steps:
      - IN: lb-mani3bg
      - IN: lb-ecscluster2
      - IN: lb-loadb2bg
        applyTo:
          - manifest: lb-mani3bg # it can only apply to one manifest
            image: lb-imglb2 # it can only apply to one image in the manifest
            port: 80
            
  - name: lb-lbDeploy3invalid
    type: deploy
    steps:
      - IN: lb-mani4invalid
      - IN: lb-ecscluster2
      - IN: lb-loadb2bg
        applyTo:
          - manifest: lb-mani4invalid # it can only apply to one manifest
          #  image: lb-imglb2 # it can only apply to one image in the manifest
           # port: 60
