triggers:

  - name: uitest-tg1
    type: trigger
    version:
      counter: 2
      
  - name: uitest-tg2
    type: trigger
    version:
      counter: 2
      
  - name: uitest-tg3
    type: trigger
    version:
      counter: 1
