jobs:

#MANIFESTS
      
  - name: srl-man1
    type: manifest
    steps:
      - IN: srl-img1
      - IN: srl-tg1
      
  - name: srl-man2
    type: manifest
    steps:
      - IN: srl-img2
      - IN: srl-tg1
      
# DEPLOYMENTS  
        
  - name: srl-ddcdeploy
    type: deploy
    steps:
      - IN: srl-man1
      - IN: srl-man2
      - IN: srl-ddccluster
