triggers:
   - name: sr-tg1
     type: trigger
     version:
       counter: 0
       
   - name: sr-tg2
     type: trigger
     version:
       counter: 0
       
   - name: sr-tg3
     type: trigger
     version:
       counter: 0
       
   - name: sr-tg4
     type: trigger
     version:
       counter: 0
       
   - name: sr-tg5
     type: trigger
     version:
       counter: 0
