jobs:
  
#MANIFESTS
      
  - name: uitest-man1
    type: manifest
    steps:
      - IN: uitest-img1
      - IN: uitest-tg1
      
  - name: uitest-man2
    type: manifest
    steps:
      - IN: uitest-img2
      - IN: uitest-tg2
      
  - name: uitest-man3mftomf
    type: manifest
    steps:
      - IN: uitest-man2
      
  - name: uitest-man4mftomf
    type: manifest
    steps:
      - IN: uitest-man1
      - IN: uitest-man3mftomf
  
