jobs:
  
#MANIFESTS
      
  - name: real-man1
    type: manifest
    steps:
      - IN: real-img1
      - IN: real-tg1
      
  - name: real-man2
    type: manifest
    steps:
      - IN: real-img2
      - IN: real-tg2
      
  - name: real-man3mftomf
    type: manifest
    steps:
      - IN: real-man2
       # switch: off
       
#DEPLOY

  - name: real-ecsdeploy
    type: deploy
    steps:
      - IN: real-man1
      - IN: real-ecscluster
      
  - name: real-ecsdeploy2
    type: deploy
    steps:
      - IN: real-release1
      - IN: real-ecscluster
      
# REALESE

  - name: real-release1
    type: release
    steps:
      - IN: real-version2
      - IN: real-ecsdeploy
      - TASK: managed
        bump: beta
      
