triggers:

  - name: real-tg1
    type: trigger
    version:
      counter: 4
      
  - name: real-tg2
    type: trigger
    version:
      counter: 1
      
  - name: real-tg3
    type: trigger
    version:
      counter: 1
