jobs:
#MANIFESTS
      
  - name: ecs-man12
    type: manifest
    steps:
      - IN: ecs-img12
      - IN: ecs-tg12
      
  - name: ecsman2-invalidimg2
    type: manifest
    steps:
      - IN: ecsimg2-tagdoesntexist2
      - IN: ecs-tg22
      
  - name: ecsman3-invalid2
    type: manifest
    steps:
      - IN: ecs-img22
        versionNumber: 369
      - IN: ecs-tg32

# DEPLOYMENTS 

  - name: ecs-deploy1up2
    type: deploy
    steps:
      - IN: ecs-man12
      - IN: ecs-cluster2
      - TASK: managed
        deployMethod: upgrade
      
  - name: ecs-deploy2bginvalidclu2
    type: deploy
    steps:
      - IN: ecs-man12
      - IN: ecsclu2-invalidclu2
      
  - name: ecs-deploy3upinvalidimg2
    type: deploy
    steps:
      - IN: ecsman2-invalidimg2
      - IN: ecs-cluster2
      - TASK: managed
        deployMethod: upgrade

  - name: ecs-deploy4bgmani2
    type: deploy
    steps:
      - IN: ecsman3-invalid2
      - IN: ecs-cluster2
      
  - name: ecs-deploy5upinvaliddopts2
    type: deploy
    steps:
      - IN: ecs-man12
      - IN: ecs-dopts2invalid2
      - IN: ecs-cluster2
      
