jobs:

#RELEASE

  - name: glab-release
    type: release
    steps:
      - IN: glab-version
      - TASK: managed
        bump: beta
      - IN: glab-man1
      #- IN: triggernotify7
      
#MANIFESTS
      
  - name: glab-man1
    type: manifest
    steps:
      - IN: glab-img1
      - IN: glab-tg1

# DEPLOYMENTS 

  - name: glab-ddcdeployup
    type: deploy
    steps:
      - IN: glab-man1
      - IN: glab-ddccluster
      
