jobs:
  
#MANIFESTS
      
  - name: real-man1
    type: manifest
    steps:
      - IN: real-img1
      - IN: real-dopts1
      - IN: real-scale1
      - IN: real-tg1
      
  - name: real-man2
    type: manifest
    steps:
      - IN: real-img2
      - IN: real-dopts1
      - IN: real-params1
      - IN: real-tg2
    flags: 
      - real-man2
      
  - name: real-man3
    type: manifest
    steps:
      - IN: real-img3
      - IN: real-dopts1
      - IN: real-params1
      - IN: real-tg3
    flags: 
      - real-man3
      
  - name: real-man4
    type: manifest
    steps:
      - IN: real-img3
      - IN: real-tg4
      
  - name: real-man5
    type: manifest
    steps:
      - IN: real-img3
      - IN: real-tg4
      
  - name: real-man6
    type: manifest
    steps:
      - IN: real-img3
     # - IN: real-dopts1
      #- IN: real-params1
      - IN: real-scale1
      - IN: real-tg5
    flags:
      - real-man6
      
  - name: real-man7
    type: manifest
    steps:
      - IN: real-release6
      
  #- name: real-man5mftomf
   # type: manifest
    #steps:
     # - IN: real-man2
      #- IN: real-man3
      #- IN: real-tg4
       # switch: off
       
#DEPLOY

  - name: real-ecsdeploy
    type: deploy
    steps:
      - IN: real-man1
      - IN: real-ecscluster
      
  - name: real-ecsdeploy2
    type: deploy
    steps:
      - IN: real-release1
      - IN: real-ecscluster
      
  - name: real-ecsdeploy3
    type: deploy
    steps:
      - IN: real-man2
      - IN: real-ecscluster
      
  - name: real-ecsdeploy4
    type: deploy
    steps:
      - IN: real-man3
      - IN: real-ecscluster
      
  - name: real-ecsdeploy5
    type: deploy
    steps:
      - IN: real-man4
      - IN: real-man5
      - IN: real-ecscluster
      
  - name: real-ecsdeploy6release
    type: deploy
    steps:
      - IN: real-release3
      - IN: real-release4
      - IN: real-ecscluster
      
# REALESE

  - name: real-release1
    type: release
    steps:
      - IN: real-version2
      - IN: real-ecsdeploy
      - TASK: managed
        bump: beta
        
  - name: real-release2
    type: release
    steps:
      - IN: real-version1
      - IN: real-ecsdeploy2
      - TASK: managed
        bump: major
        
  - name: real-release3
    type: release
    steps:
      - IN: real-version3
      - IN: real-ecsdeploy3
      - TASK: managed
        bump: beta
        
  - name: real-release4
    type: release
    steps:
      - IN: real-version4
      - IN: real-ecsdeploy4
      - TASK: managed
        bump: alpha
        
  - name: real-release5
    type: release
    steps:
      - IN: real-version1
      - IN: real-ecsdeploy6release
      - TASK: managed
        bump: major
        
  - name: real-release6
    type: release
    steps:
      - IN: real-version6
      - IN: real-man6
      - TASK: managed
        bump: rc

  - name: real-release7
    type: release
    steps:
      - IN: real-version5
      - IN: real-man7
      - TASK: managed
        bump: major
