triggers:
   - name: gke-tg1
     type: trigger
     version:
       counter: 0
       
   - name: gke-tg2
     type: trigger
     version:
       counter: 0
       
   - name: gke-tg3
     type: trigger
     version:
       counter: 0
       
   - name: gke-tg4
     type: trigger
     version:
       counter: 0
       
   - name: gke-tg5
     type: trigger
     version:
       counter: 0
